name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/event-planner
            git pull origin dev
            docker stop event-planner
            docker rm event-planner
            docker build -t eventplanner:latest .
            docker run -d -p 80:80 -e APP_PORT="80" -e DB_PORT="3306" -e DB_DRIVER="mysql" -e DB_NAME="eventplanningdb" -e DB_ADDRESS="${{ secrets.DBHOST }}" -e DB_USERNAME="${{ secrets.DBUSERNAME }}" -e DB_PASSWORD="${{ secrets.DBPASSWORD }}" -e AWS_S3_REGION="${{ secrets.AWS_S3_REGION }}" -e AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}" -e AWS_S3_KEY="${{ secrets.AWS_S3_KEY }}" -e AWS_S3_ACCESS="${{ secrets.AWS_S3_ACCESS }}" --name event-planner eventplanner:latest
